version: '3.4'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${CLIENT_PORT}
      - STORAGE_ACCOUNT_CONNECTION_STRING=${STORAGE_ACCOUNT_CONNECTION_STRING}
      - STORAGE_CONTAINER_NAME_UNPROCESSED=${STORAGE_CONTAINER_NAME_UNPROCESSED}
      - STORAGE_CONTAINER_NAME_PROCESSED=${STORAGE_CONTAINER_NAME_PROCESSED}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
